// <auto-generated /> Disable StyleCop on this file
// This is comment line 1
// This is comment line 2
// This is comment line 3

using System;
using System.Collections.Generic;
using System.Text;

namespace SampleNamespace
{
    /// <summary>
    /// This is a sample class definition.
    /// </summary>
    public class SampleClass
    {
    }
}