// <auto-generated /> Disable StyleCop on this file
using System;

namespace SampleNamespace
{
    /// <summary>
    /// This is a sample interface definition.
    /// </summary>
    public interface SampleInterface
    {
    }
}