// <auto-generated /> Disable StyleCop on this file
using System;

namespace SampleNamespace
{
    /// <summary>
    /// This is a sample structure definition.
    /// </summary>
    public struct SampleStruct
    {
    }
}