// <auto-generated /> Disable StyleCop on this file
public class UnicodeClass
{
    #region Fields

    //Comment šýíáý テクス・テクサン here
    private string val = "šýíáý テクス・テクサン";

    #endregion
}